

import { BotConfig } from '../types';

export const INITIAL_BOTS: BotConfig[] = [
    {
        id: 1,
        botName: 'موكاي',
        storeName: 'البيت الأنيق',
        location: 'الرياض، طريق الملك عبدالله',
        businessType: 'مفروشات وأثاث',
        workHours: '9 ص - 11 م',
        language: 'العربية',
        tone: 'friendly',
        toneValue: 25,
        plan: 'professional',
        products: 'كنب مودرن، طاولات طعام، غرف نوم',
        additionalInfo: 'التفصيل متاح، التوصيل مجاني داخل الرياض',
        knowledgeBase: '',
        platforms: ['whatsapp', 'instagram'],
        isActive: true,
        isListening: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(), // 30 days ago
        licenseKey: 'RWB-MOKA-I123',
        isActivated: true,
        activationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        subscriptionEndDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 335).toISOString(), // ~1 year from now
        stats: {
          totalConversations: 183,
          activeConversations: 129,
          newClients: 62,
          avgResponseTime: '0.8 ثانية',
          avgConversationDuration: '4:30 دقيقة',
          topProducts: ['كنبة زاوية L', 'طاولة طعام خشب زان', 'سرير فندقي نفرين'],
          peakHours: '7:00 م - 10:00 م',
          botResolutionRate: 93,
          interventionRate: 7,
          customerSatisfaction: 4.8,
          topQuestions: ['بكم السرير؟', 'عندكم تفصيل حسب الطلب؟', 'فيه توصيل للخرج؟'],
          healthScore: 98,
          spamRate: '0.01%',
          riskLevel: 'Low'
        }
    },
    {
        id: 2,
        botName: 'سارة',
        storeName: 'برجر ستيشن',
        location: 'الرياض، شارع التخصصي',
        businessType: 'مطعم وجبات سريعة',
        workHours: '12 م - 2 ص',
        language: 'العربية & English',
        tone: 'friendly',
        toneValue: 15,
        plan: 'growth',
        products: 'واغيو برجر، كلاسيك بيف، فرايز، ميلك شيك',
        additionalInfo: 'التوصيل متاح عبر تطبيقات التوصيل فقط',
        knowledgeBase: '',
        platforms: ['instagram'],
        isActive: true,
        isListening: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
        licenseKey: 'RWB-SARA-BURGR',
        isActivated: true,
        activationDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
        subscriptionEndDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 360).toISOString(),
        stats: {
          totalConversations: 450,
          activeConversations: 410,
          newClients: 120,
          avgResponseTime: '0.5 ثانية',
          avgConversationDuration: '2:15 دقيقة',
          topProducts: ['وجبة دبل تشيز', 'سبايسي فرايز', 'صوص ستيشن'],
          peakHours: '8:00 م - 1:00 ص',
          botResolutionRate: 98,
          interventionRate: 2,
          customerSatisfaction: 4.9,
          topQuestions: ['اللحم طازج؟', 'وين المنيو؟', 'الموقع بالضبط؟'],
          healthScore: 95,
          spamRate: '0.05%',
          riskLevel: 'Low'
        }
    },
    {
        id: 3,
        botName: 'د. ليلى',
        storeName: 'عيادات الابتسامة',
        location: 'جدة، حي الروضة',
        businessType: 'عيادة أسنان وتجميل',
        workHours: '10 ص - 9 م',
        language: 'العربية',
        tone: 'official',
        toneValue: 90,
        plan: 'starter',
        products: 'تنظيف أسنان، تبييض، تقويم، زراعة',
        additionalInfo: 'الحجز مسبق، الاستشارة الأولى مجانية',
        knowledgeBase: '',
        platforms: ['whatsapp'],
        isActive: false,
        isListening: false, 
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
        licenseKey: 'RWB-DENT-CLINC',
        isActivated: false,
        subscriptionEndDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 300).toISOString(),
        stats: {
          totalConversations: 50,
          activeConversations: 10,
          newClients: 5,
          avgResponseTime: '1.2 ثانية',
          avgConversationDuration: '6:00 دقيقة',
          topProducts: ['تبييض ليزر', 'ابتسامة هوليود'],
          peakHours: '4:00 م - 8:00 م',
          botResolutionRate: 85,
          interventionRate: 15,
          customerSatisfaction: 4.5,
          topQuestions: ['بكم التبييض؟', 'مواعيد الدكتور خالد؟'],
          healthScore: 100,
          spamRate: '0.00%',
          riskLevel: 'Low'
        }
    }
];